### ISSUE TITLE
Resource limits for ARC

### ISSUE THREAD

**Issue by cboettig** [boettiger-lab/k8s#4]
- ARC doesn't seem to handle resource limits when user specifies a container.

- not sure if we can disable container use though in ARC?  needs testing (seems that mode must be either `dind` or `kubernetes`, the latter requires a `container` field in the action yaml, and also doesn't recognize command-line docker options like below.    

Individual tasks can set action limits, probably the best way to go at this point.

e.g. for EFI config: 

```
    runs-on: efi-cirrus
    container: 
      # IMPORTANT.  Please set a memory limit <= 45 GB.
      image: eco4cast/rocker-neon4cast:latest
      options: --memory="15g"
    steps:
```

(FIXME add links to GH ARC docs and issues here)
